version: '3'
services:
    
    jenkins:
        image: jenkins/jenkins
        ports:
        - 8080:8080
        volumes:
        - .docker/jenkins_data:/var/jenkins_home
        - ${PROJECT_VOLUME:-.}:/home/project
        
    registry:
        restart: always
        image: registry:2
        ports:
            - 5001:5000